<?php
/**
 * PaymentAllocationInvoicedBooking
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cinolla Client API
 *
 * Welcome to Cinolla Client API documentation for version 3. Please see below for the available API endpoints and their required parameters and responses. If you have any questions, please contact [support@cinolla.com](mailto:support@cinolla.com).
 *
 * The version of the OpenAPI document: 3.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Cinolla\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SynergiTech\Cinolla\ObjectSerializer;

/**
 * PaymentAllocationInvoicedBooking Class Doc Comment
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PaymentAllocationInvoicedBooking implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PaymentAllocation_invoicedBooking';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'invoiceNumber' => 'int',
        'invoiceType' => 'string',
        'status' => 'string',
        'totalNet' => 'string',
        'totalGross' => 'string',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime',
        'invoiceDate' => '\DateTime',
        'invoiceDue' => '\DateTime',
        'type' => 'string',
        'deliveryAddressName' => 'string',
        'deliveryAddressOrganisation' => 'string',
        'deliveryAddressAddress1' => 'string',
        'deliveryAddressAddress2' => 'string',
        'deliveryAddressTown' => 'string',
        'deliveryAddressCounty' => 'string',
        'deliveryAddressPostcode' => 'string',
        'deliveryAddressCountry' => 'string',
        'billingAddressName' => 'string',
        'billingAddressOrganisation' => 'string',
        'billingAddressAddress1' => 'string',
        'billingAddressAddress2' => 'string',
        'billingAddressTown' => 'string',
        'billingAddressCounty' => 'string',
        'billingAddressPostcode' => 'string',
        'billingAddressCountry' => 'string',
        'void' => 'bool',
        'voidAt' => '\DateTime',
        'reference' => 'string',
        'poReference' => 'string',
        'outstandingAmount' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'invoiceNumber' => null,
        'invoiceType' => null,
        'status' => null,
        'totalNet' => null,
        'totalGross' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time',
        'invoiceDate' => 'date-time',
        'invoiceDue' => 'date-time',
        'type' => null,
        'deliveryAddressName' => null,
        'deliveryAddressOrganisation' => null,
        'deliveryAddressAddress1' => null,
        'deliveryAddressAddress2' => null,
        'deliveryAddressTown' => null,
        'deliveryAddressCounty' => null,
        'deliveryAddressPostcode' => null,
        'deliveryAddressCountry' => null,
        'billingAddressName' => null,
        'billingAddressOrganisation' => null,
        'billingAddressAddress1' => null,
        'billingAddressAddress2' => null,
        'billingAddressTown' => null,
        'billingAddressCounty' => null,
        'billingAddressPostcode' => null,
        'billingAddressCountry' => null,
        'void' => null,
        'voidAt' => 'date-time',
        'reference' => null,
        'poReference' => null,
        'outstandingAmount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'invoiceNumber' => true,
        'invoiceType' => false,
        'status' => true,
        'totalNet' => true,
        'totalGross' => false,
        'createdAt' => false,
        'updatedAt' => false,
        'invoiceDate' => false,
        'invoiceDue' => false,
        'type' => true,
        'deliveryAddressName' => true,
        'deliveryAddressOrganisation' => true,
        'deliveryAddressAddress1' => true,
        'deliveryAddressAddress2' => true,
        'deliveryAddressTown' => true,
        'deliveryAddressCounty' => true,
        'deliveryAddressPostcode' => true,
        'deliveryAddressCountry' => true,
        'billingAddressName' => true,
        'billingAddressOrganisation' => true,
        'billingAddressAddress1' => true,
        'billingAddressAddress2' => true,
        'billingAddressTown' => true,
        'billingAddressCounty' => true,
        'billingAddressPostcode' => true,
        'billingAddressCountry' => true,
        'void' => true,
        'voidAt' => true,
        'reference' => true,
        'poReference' => true,
        'outstandingAmount' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'invoiceNumber' => 'invoiceNumber',
        'invoiceType' => 'invoiceType',
        'status' => 'status',
        'totalNet' => 'totalNet',
        'totalGross' => 'totalGross',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt',
        'invoiceDate' => 'invoiceDate',
        'invoiceDue' => 'invoiceDue',
        'type' => 'type',
        'deliveryAddressName' => 'deliveryAddressName',
        'deliveryAddressOrganisation' => 'deliveryAddressOrganisation',
        'deliveryAddressAddress1' => 'deliveryAddressAddress1',
        'deliveryAddressAddress2' => 'deliveryAddressAddress2',
        'deliveryAddressTown' => 'deliveryAddressTown',
        'deliveryAddressCounty' => 'deliveryAddressCounty',
        'deliveryAddressPostcode' => 'deliveryAddressPostcode',
        'deliveryAddressCountry' => 'deliveryAddressCountry',
        'billingAddressName' => 'billingAddressName',
        'billingAddressOrganisation' => 'billingAddressOrganisation',
        'billingAddressAddress1' => 'billingAddressAddress1',
        'billingAddressAddress2' => 'billingAddressAddress2',
        'billingAddressTown' => 'billingAddressTown',
        'billingAddressCounty' => 'billingAddressCounty',
        'billingAddressPostcode' => 'billingAddressPostcode',
        'billingAddressCountry' => 'billingAddressCountry',
        'void' => 'void',
        'voidAt' => 'voidAt',
        'reference' => 'reference',
        'poReference' => 'poReference',
        'outstandingAmount' => 'outstandingAmount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'invoiceNumber' => 'setInvoiceNumber',
        'invoiceType' => 'setInvoiceType',
        'status' => 'setStatus',
        'totalNet' => 'setTotalNet',
        'totalGross' => 'setTotalGross',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt',
        'invoiceDate' => 'setInvoiceDate',
        'invoiceDue' => 'setInvoiceDue',
        'type' => 'setType',
        'deliveryAddressName' => 'setDeliveryAddressName',
        'deliveryAddressOrganisation' => 'setDeliveryAddressOrganisation',
        'deliveryAddressAddress1' => 'setDeliveryAddressAddress1',
        'deliveryAddressAddress2' => 'setDeliveryAddressAddress2',
        'deliveryAddressTown' => 'setDeliveryAddressTown',
        'deliveryAddressCounty' => 'setDeliveryAddressCounty',
        'deliveryAddressPostcode' => 'setDeliveryAddressPostcode',
        'deliveryAddressCountry' => 'setDeliveryAddressCountry',
        'billingAddressName' => 'setBillingAddressName',
        'billingAddressOrganisation' => 'setBillingAddressOrganisation',
        'billingAddressAddress1' => 'setBillingAddressAddress1',
        'billingAddressAddress2' => 'setBillingAddressAddress2',
        'billingAddressTown' => 'setBillingAddressTown',
        'billingAddressCounty' => 'setBillingAddressCounty',
        'billingAddressPostcode' => 'setBillingAddressPostcode',
        'billingAddressCountry' => 'setBillingAddressCountry',
        'void' => 'setVoid',
        'voidAt' => 'setVoidAt',
        'reference' => 'setReference',
        'poReference' => 'setPoReference',
        'outstandingAmount' => 'setOutstandingAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'invoiceNumber' => 'getInvoiceNumber',
        'invoiceType' => 'getInvoiceType',
        'status' => 'getStatus',
        'totalNet' => 'getTotalNet',
        'totalGross' => 'getTotalGross',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt',
        'invoiceDate' => 'getInvoiceDate',
        'invoiceDue' => 'getInvoiceDue',
        'type' => 'getType',
        'deliveryAddressName' => 'getDeliveryAddressName',
        'deliveryAddressOrganisation' => 'getDeliveryAddressOrganisation',
        'deliveryAddressAddress1' => 'getDeliveryAddressAddress1',
        'deliveryAddressAddress2' => 'getDeliveryAddressAddress2',
        'deliveryAddressTown' => 'getDeliveryAddressTown',
        'deliveryAddressCounty' => 'getDeliveryAddressCounty',
        'deliveryAddressPostcode' => 'getDeliveryAddressPostcode',
        'deliveryAddressCountry' => 'getDeliveryAddressCountry',
        'billingAddressName' => 'getBillingAddressName',
        'billingAddressOrganisation' => 'getBillingAddressOrganisation',
        'billingAddressAddress1' => 'getBillingAddressAddress1',
        'billingAddressAddress2' => 'getBillingAddressAddress2',
        'billingAddressTown' => 'getBillingAddressTown',
        'billingAddressCounty' => 'getBillingAddressCounty',
        'billingAddressPostcode' => 'getBillingAddressPostcode',
        'billingAddressCountry' => 'getBillingAddressCountry',
        'void' => 'getVoid',
        'voidAt' => 'getVoidAt',
        'reference' => 'getReference',
        'poReference' => 'getPoReference',
        'outstandingAmount' => 'getOutstandingAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const INVOICE_TYPE_STANDARD = 'standard';
    public const INVOICE_TYPE_DEPOSIT = 'deposit';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInvoiceTypeAllowableValues()
    {
        return [
            self::INVOICE_TYPE_STANDARD,
            self::INVOICE_TYPE_DEPOSIT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('invoiceNumber', $data ?? [], null);
        $this->setIfExists('invoiceType', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], 'draft');
        $this->setIfExists('totalNet', $data ?? [], null);
        $this->setIfExists('totalGross', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('invoiceDate', $data ?? [], null);
        $this->setIfExists('invoiceDue', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('deliveryAddressName', $data ?? [], null);
        $this->setIfExists('deliveryAddressOrganisation', $data ?? [], null);
        $this->setIfExists('deliveryAddressAddress1', $data ?? [], null);
        $this->setIfExists('deliveryAddressAddress2', $data ?? [], null);
        $this->setIfExists('deliveryAddressTown', $data ?? [], null);
        $this->setIfExists('deliveryAddressCounty', $data ?? [], null);
        $this->setIfExists('deliveryAddressPostcode', $data ?? [], null);
        $this->setIfExists('deliveryAddressCountry', $data ?? [], null);
        $this->setIfExists('billingAddressName', $data ?? [], null);
        $this->setIfExists('billingAddressOrganisation', $data ?? [], null);
        $this->setIfExists('billingAddressAddress1', $data ?? [], null);
        $this->setIfExists('billingAddressAddress2', $data ?? [], null);
        $this->setIfExists('billingAddressTown', $data ?? [], null);
        $this->setIfExists('billingAddressCounty', $data ?? [], null);
        $this->setIfExists('billingAddressPostcode', $data ?? [], null);
        $this->setIfExists('billingAddressCountry', $data ?? [], null);
        $this->setIfExists('void', $data ?? [], null);
        $this->setIfExists('voidAt', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('poReference', $data ?? [], null);
        $this->setIfExists('outstandingAmount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['invoiceType'] === null) {
            $invalidProperties[] = "'invoiceType' can't be null";
        }
        $allowedValues = $this->getInvoiceTypeAllowableValues();
        if (!is_null($this->container['invoiceType']) && !in_array($this->container['invoiceType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'invoiceType', must be one of '%s'",
                $this->container['invoiceType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['totalGross'] === null) {
            $invalidProperties[] = "'totalGross' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        if ($this->container['invoiceDate'] === null) {
            $invalidProperties[] = "'invoiceDate' can't be null";
        }
        if ($this->container['invoiceDue'] === null) {
            $invalidProperties[] = "'invoiceDue' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId(int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets invoiceNumber
     *
     * @return int|null
     */
    public function getInvoiceNumber(): ?int
    {
        return $this->container['invoiceNumber'];
    }

    /**
     * Sets invoiceNumber
     *
     * @param int|null $invoiceNumber invoiceNumber
     *
     * @return $this
     */
    public function setInvoiceNumber(?int $invoiceNumber): static
    {
        if (is_null($invoiceNumber)) {
            array_push($this->openAPINullablesSetToNull, 'invoiceNumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoiceNumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoiceNumber'] = $invoiceNumber;

        return $this;
    }

    /**
     * Gets invoiceType
     *
     * @return string
     */
    public function getInvoiceType(): string
    {
        return $this->container['invoiceType'];
    }

    /**
     * Sets invoiceType
     *
     * @param string $invoiceType invoiceType
     *
     * @return $this
     */
    public function setInvoiceType(string $invoiceType): static
    {
        if (is_null($invoiceType)) {
            throw new InvalidArgumentException('non-nullable invoiceType cannot be null');
        }
        $allowedValues = $this->getInvoiceTypeAllowableValues();
        if (!in_array($invoiceType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'invoiceType', must be one of '%s'",
                    $invoiceType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['invoiceType'] = $invoiceType;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets totalNet
     *
     * @return string|null
     */
    public function getTotalNet(): ?string
    {
        return $this->container['totalNet'];
    }

    /**
     * Sets totalNet
     *
     * @param string|null $totalNet totalNet
     *
     * @return $this
     */
    public function setTotalNet(?string $totalNet): static
    {
        if (is_null($totalNet)) {
            array_push($this->openAPINullablesSetToNull, 'totalNet');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('totalNet', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['totalNet'] = $totalNet;

        return $this;
    }

    /**
     * Gets totalGross
     *
     * @return string
     */
    public function getTotalGross(): string
    {
        return $this->container['totalGross'];
    }

    /**
     * Sets totalGross
     *
     * @param string $totalGross totalGross
     *
     * @return $this
     */
    public function setTotalGross(string $totalGross): static
    {
        if (is_null($totalGross)) {
            throw new InvalidArgumentException('non-nullable totalGross cannot be null');
        }


        $this->container['totalGross'] = $totalGross;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt updatedAt
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets invoiceDate
     *
     * @return \DateTime
     */
    public function getInvoiceDate(): \DateTime
    {
        return $this->container['invoiceDate'];
    }

    /**
     * Sets invoiceDate
     *
     * @param \DateTime $invoiceDate invoiceDate
     *
     * @return $this
     */
    public function setInvoiceDate(\DateTime $invoiceDate): static
    {
        if (is_null($invoiceDate)) {
            throw new InvalidArgumentException('non-nullable invoiceDate cannot be null');
        }
        $this->container['invoiceDate'] = $invoiceDate;

        return $this;
    }

    /**
     * Gets invoiceDue
     *
     * @return \DateTime
     */
    public function getInvoiceDue(): \DateTime
    {
        return $this->container['invoiceDue'];
    }

    /**
     * Sets invoiceDue
     *
     * @param \DateTime $invoiceDue invoiceDue
     *
     * @return $this
     */
    public function setInvoiceDue(\DateTime $invoiceDue): static
    {
        if (is_null($invoiceDue)) {
            throw new InvalidArgumentException('non-nullable invoiceDue cannot be null');
        }
        $this->container['invoiceDue'] = $invoiceDue;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return $this
     */
    public function setType(?string $type): static
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets deliveryAddressName
     *
     * @return string|null
     */
    public function getDeliveryAddressName(): ?string
    {
        return $this->container['deliveryAddressName'];
    }

    /**
     * Sets deliveryAddressName
     *
     * @param string|null $deliveryAddressName deliveryAddressName
     *
     * @return $this
     */
    public function setDeliveryAddressName(?string $deliveryAddressName): static
    {
        if (is_null($deliveryAddressName)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressName'] = $deliveryAddressName;

        return $this;
    }

    /**
     * Gets deliveryAddressOrganisation
     *
     * @return string|null
     */
    public function getDeliveryAddressOrganisation(): ?string
    {
        return $this->container['deliveryAddressOrganisation'];
    }

    /**
     * Sets deliveryAddressOrganisation
     *
     * @param string|null $deliveryAddressOrganisation deliveryAddressOrganisation
     *
     * @return $this
     */
    public function setDeliveryAddressOrganisation(?string $deliveryAddressOrganisation): static
    {
        if (is_null($deliveryAddressOrganisation)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressOrganisation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressOrganisation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressOrganisation'] = $deliveryAddressOrganisation;

        return $this;
    }

    /**
     * Gets deliveryAddressAddress1
     *
     * @return string|null
     */
    public function getDeliveryAddressAddress1(): ?string
    {
        return $this->container['deliveryAddressAddress1'];
    }

    /**
     * Sets deliveryAddressAddress1
     *
     * @param string|null $deliveryAddressAddress1 deliveryAddressAddress1
     *
     * @return $this
     */
    public function setDeliveryAddressAddress1(?string $deliveryAddressAddress1): static
    {
        if (is_null($deliveryAddressAddress1)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressAddress1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressAddress1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressAddress1'] = $deliveryAddressAddress1;

        return $this;
    }

    /**
     * Gets deliveryAddressAddress2
     *
     * @return string|null
     */
    public function getDeliveryAddressAddress2(): ?string
    {
        return $this->container['deliveryAddressAddress2'];
    }

    /**
     * Sets deliveryAddressAddress2
     *
     * @param string|null $deliveryAddressAddress2 deliveryAddressAddress2
     *
     * @return $this
     */
    public function setDeliveryAddressAddress2(?string $deliveryAddressAddress2): static
    {
        if (is_null($deliveryAddressAddress2)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressAddress2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressAddress2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressAddress2'] = $deliveryAddressAddress2;

        return $this;
    }

    /**
     * Gets deliveryAddressTown
     *
     * @return string|null
     */
    public function getDeliveryAddressTown(): ?string
    {
        return $this->container['deliveryAddressTown'];
    }

    /**
     * Sets deliveryAddressTown
     *
     * @param string|null $deliveryAddressTown deliveryAddressTown
     *
     * @return $this
     */
    public function setDeliveryAddressTown(?string $deliveryAddressTown): static
    {
        if (is_null($deliveryAddressTown)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressTown');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressTown', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressTown'] = $deliveryAddressTown;

        return $this;
    }

    /**
     * Gets deliveryAddressCounty
     *
     * @return string|null
     */
    public function getDeliveryAddressCounty(): ?string
    {
        return $this->container['deliveryAddressCounty'];
    }

    /**
     * Sets deliveryAddressCounty
     *
     * @param string|null $deliveryAddressCounty deliveryAddressCounty
     *
     * @return $this
     */
    public function setDeliveryAddressCounty(?string $deliveryAddressCounty): static
    {
        if (is_null($deliveryAddressCounty)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressCounty');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressCounty', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressCounty'] = $deliveryAddressCounty;

        return $this;
    }

    /**
     * Gets deliveryAddressPostcode
     *
     * @return string|null
     */
    public function getDeliveryAddressPostcode(): ?string
    {
        return $this->container['deliveryAddressPostcode'];
    }

    /**
     * Sets deliveryAddressPostcode
     *
     * @param string|null $deliveryAddressPostcode deliveryAddressPostcode
     *
     * @return $this
     */
    public function setDeliveryAddressPostcode(?string $deliveryAddressPostcode): static
    {
        if (is_null($deliveryAddressPostcode)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressPostcode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressPostcode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressPostcode'] = $deliveryAddressPostcode;

        return $this;
    }

    /**
     * Gets deliveryAddressCountry
     *
     * @return string|null
     */
    public function getDeliveryAddressCountry(): ?string
    {
        return $this->container['deliveryAddressCountry'];
    }

    /**
     * Sets deliveryAddressCountry
     *
     * @param string|null $deliveryAddressCountry deliveryAddressCountry
     *
     * @return $this
     */
    public function setDeliveryAddressCountry(?string $deliveryAddressCountry): static
    {
        if (is_null($deliveryAddressCountry)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryAddressCountry');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryAddressCountry', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryAddressCountry'] = $deliveryAddressCountry;

        return $this;
    }

    /**
     * Gets billingAddressName
     *
     * @return string|null
     */
    public function getBillingAddressName(): ?string
    {
        return $this->container['billingAddressName'];
    }

    /**
     * Sets billingAddressName
     *
     * @param string|null $billingAddressName billingAddressName
     *
     * @return $this
     */
    public function setBillingAddressName(?string $billingAddressName): static
    {
        if (is_null($billingAddressName)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressName'] = $billingAddressName;

        return $this;
    }

    /**
     * Gets billingAddressOrganisation
     *
     * @return string|null
     */
    public function getBillingAddressOrganisation(): ?string
    {
        return $this->container['billingAddressOrganisation'];
    }

    /**
     * Sets billingAddressOrganisation
     *
     * @param string|null $billingAddressOrganisation billingAddressOrganisation
     *
     * @return $this
     */
    public function setBillingAddressOrganisation(?string $billingAddressOrganisation): static
    {
        if (is_null($billingAddressOrganisation)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressOrganisation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressOrganisation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressOrganisation'] = $billingAddressOrganisation;

        return $this;
    }

    /**
     * Gets billingAddressAddress1
     *
     * @return string|null
     */
    public function getBillingAddressAddress1(): ?string
    {
        return $this->container['billingAddressAddress1'];
    }

    /**
     * Sets billingAddressAddress1
     *
     * @param string|null $billingAddressAddress1 billingAddressAddress1
     *
     * @return $this
     */
    public function setBillingAddressAddress1(?string $billingAddressAddress1): static
    {
        if (is_null($billingAddressAddress1)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressAddress1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressAddress1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressAddress1'] = $billingAddressAddress1;

        return $this;
    }

    /**
     * Gets billingAddressAddress2
     *
     * @return string|null
     */
    public function getBillingAddressAddress2(): ?string
    {
        return $this->container['billingAddressAddress2'];
    }

    /**
     * Sets billingAddressAddress2
     *
     * @param string|null $billingAddressAddress2 billingAddressAddress2
     *
     * @return $this
     */
    public function setBillingAddressAddress2(?string $billingAddressAddress2): static
    {
        if (is_null($billingAddressAddress2)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressAddress2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressAddress2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressAddress2'] = $billingAddressAddress2;

        return $this;
    }

    /**
     * Gets billingAddressTown
     *
     * @return string|null
     */
    public function getBillingAddressTown(): ?string
    {
        return $this->container['billingAddressTown'];
    }

    /**
     * Sets billingAddressTown
     *
     * @param string|null $billingAddressTown billingAddressTown
     *
     * @return $this
     */
    public function setBillingAddressTown(?string $billingAddressTown): static
    {
        if (is_null($billingAddressTown)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressTown');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressTown', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressTown'] = $billingAddressTown;

        return $this;
    }

    /**
     * Gets billingAddressCounty
     *
     * @return string|null
     */
    public function getBillingAddressCounty(): ?string
    {
        return $this->container['billingAddressCounty'];
    }

    /**
     * Sets billingAddressCounty
     *
     * @param string|null $billingAddressCounty billingAddressCounty
     *
     * @return $this
     */
    public function setBillingAddressCounty(?string $billingAddressCounty): static
    {
        if (is_null($billingAddressCounty)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressCounty');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressCounty', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressCounty'] = $billingAddressCounty;

        return $this;
    }

    /**
     * Gets billingAddressPostcode
     *
     * @return string|null
     */
    public function getBillingAddressPostcode(): ?string
    {
        return $this->container['billingAddressPostcode'];
    }

    /**
     * Sets billingAddressPostcode
     *
     * @param string|null $billingAddressPostcode billingAddressPostcode
     *
     * @return $this
     */
    public function setBillingAddressPostcode(?string $billingAddressPostcode): static
    {
        if (is_null($billingAddressPostcode)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressPostcode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressPostcode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressPostcode'] = $billingAddressPostcode;

        return $this;
    }

    /**
     * Gets billingAddressCountry
     *
     * @return string|null
     */
    public function getBillingAddressCountry(): ?string
    {
        return $this->container['billingAddressCountry'];
    }

    /**
     * Sets billingAddressCountry
     *
     * @param string|null $billingAddressCountry billingAddressCountry
     *
     * @return $this
     */
    public function setBillingAddressCountry(?string $billingAddressCountry): static
    {
        if (is_null($billingAddressCountry)) {
            array_push($this->openAPINullablesSetToNull, 'billingAddressCountry');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('billingAddressCountry', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['billingAddressCountry'] = $billingAddressCountry;

        return $this;
    }

    /**
     * Gets void
     *
     * @return bool|null
     */
    public function getVoid(): ?bool
    {
        return $this->container['void'];
    }

    /**
     * Sets void
     *
     * @param bool|null $void void
     *
     * @return $this
     */
    public function setVoid(?bool $void): static
    {
        if (is_null($void)) {
            array_push($this->openAPINullablesSetToNull, 'void');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('void', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['void'] = $void;

        return $this;
    }

    /**
     * Gets voidAt
     *
     * @return \DateTime|null
     */
    public function getVoidAt(): ?\DateTime
    {
        return $this->container['voidAt'];
    }

    /**
     * Sets voidAt
     *
     * @param \DateTime|null $voidAt voidAt
     *
     * @return $this
     */
    public function setVoidAt(?\DateTime $voidAt): static
    {
        if (is_null($voidAt)) {
            array_push($this->openAPINullablesSetToNull, 'voidAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('voidAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['voidAt'] = $voidAt;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference(): ?string
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference reference
     *
     * @return $this
     */
    public function setReference(?string $reference): static
    {
        if (is_null($reference)) {
            array_push($this->openAPINullablesSetToNull, 'reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets poReference
     *
     * @return string|null
     */
    public function getPoReference(): ?string
    {
        return $this->container['poReference'];
    }

    /**
     * Sets poReference
     *
     * @param string|null $poReference poReference
     *
     * @return $this
     */
    public function setPoReference(?string $poReference): static
    {
        if (is_null($poReference)) {
            array_push($this->openAPINullablesSetToNull, 'poReference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('poReference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['poReference'] = $poReference;

        return $this;
    }

    /**
     * Gets outstandingAmount
     *
     * @return string|null
     */
    public function getOutstandingAmount(): ?string
    {
        return $this->container['outstandingAmount'];
    }

    /**
     * Sets outstandingAmount
     *
     * @param string|null $outstandingAmount outstandingAmount
     *
     * @return $this
     */
    public function setOutstandingAmount(?string $outstandingAmount): static
    {
        if (is_null($outstandingAmount)) {
            array_push($this->openAPINullablesSetToNull, 'outstandingAmount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('outstandingAmount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['outstandingAmount'] = $outstandingAmount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


