<?php
/**
 * CoursesApi
 * PHP version 8.1
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cinolla Client API
 *
 * Welcome to Cinolla Client API documentation for version 3. Please see below for the available API endpoints and their required parameters and responses. If you have any questions, please contact [support@cinolla.com](mailto:support@cinolla.com).
 *
 * The version of the OpenAPI document: 3.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Cinolla\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use SynergiTech\Cinolla\ApiException;
use SynergiTech\Cinolla\Configuration;
use SynergiTech\Cinolla\HeaderSelector;
use SynergiTech\Cinolla\ObjectSerializer;

/**
 * CoursesApi Class Doc Comment
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CoursesApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getCourseRuns' => [
            'application/json',
        ],
        'getCourses' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getCourseRuns
     *
     * Returns a collection of Course Runs for a given course
     *
     * @param  string $id id (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  \DateTime|null $startDate Start date of a date range. Used in conjunction with endDate to create a date range to filter by. (optional)
     * @param  \DateTime|null $endDate End date of a date range. Used in conjunction with startDate to create a date range to filter by. (optional)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourseRuns'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Cinolla\Model\CourseRun[]
     */
    public function getCourseRuns(
        string $id,
        ?int $offset = 0,
        ?int $limit = 100,
        ?\DateTime $startDate = null,
        ?\DateTime $endDate = null,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourseRuns'][0]
    ): array
    {
        list($response) = $this->getCourseRunsWithHttpInfo($id, $offset, $limit, $startDate, $endDate, $sellOnPortal, $contentType);
        return $response;
    }

    /**
     * Operation getCourseRunsWithHttpInfo
     *
     * Returns a collection of Course Runs for a given course
     *
     * @param  string $id (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  \DateTime|null $startDate Start date of a date range. Used in conjunction with endDate to create a date range to filter by. (optional)
     * @param  \DateTime|null $endDate End date of a date range. Used in conjunction with startDate to create a date range to filter by. (optional)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourseRuns'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Cinolla\Model\CourseRun[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCourseRunsWithHttpInfo(
        string $id,
        ?int $offset = 0,
        ?int $limit = 100,
        ?\DateTime $startDate = null,
        ?\DateTime $endDate = null,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourseRuns'][0]
    ): array
    {
        $request = $this->getCourseRunsRequest($id, $offset, $limit, $startDate, $endDate, $sellOnPortal, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Cinolla\Model\CourseRun[]', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Cinolla\Model\CourseRun[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Cinolla\Model\CourseRun[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Cinolla\Model\CourseRun[]';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Cinolla\Model\CourseRun[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCourseRunsAsync
     *
     * Returns a collection of Course Runs for a given course
     *
     * @param  string $id (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  \DateTime|null $startDate Start date of a date range. Used in conjunction with endDate to create a date range to filter by. (optional)
     * @param  \DateTime|null $endDate End date of a date range. Used in conjunction with startDate to create a date range to filter by. (optional)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourseRuns'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCourseRunsAsync(
        string $id,
        ?int $offset = 0,
        ?int $limit = 100,
        ?\DateTime $startDate = null,
        ?\DateTime $endDate = null,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourseRuns'][0]
    ): PromiseInterface
    {
        return $this->getCourseRunsAsyncWithHttpInfo($id, $offset, $limit, $startDate, $endDate, $sellOnPortal, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCourseRunsAsyncWithHttpInfo
     *
     * Returns a collection of Course Runs for a given course
     *
     * @param  string $id (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  \DateTime|null $startDate Start date of a date range. Used in conjunction with endDate to create a date range to filter by. (optional)
     * @param  \DateTime|null $endDate End date of a date range. Used in conjunction with startDate to create a date range to filter by. (optional)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourseRuns'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCourseRunsAsyncWithHttpInfo(
        string $id,
        ?int $offset = 0,
        ?int $limit = 100,
        ?\DateTime $startDate = null,
        ?\DateTime $endDate = null,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourseRuns'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Cinolla\Model\CourseRun[]';
        $request = $this->getCourseRunsRequest($id, $offset, $limit, $startDate, $endDate, $sellOnPortal, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCourseRuns'
     *
     * @param  string $id (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  \DateTime|null $startDate Start date of a date range. Used in conjunction with endDate to create a date range to filter by. (optional)
     * @param  \DateTime|null $endDate End date of a date range. Used in conjunction with startDate to create a date range to filter by. (optional)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourseRuns'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCourseRunsRequest(
        string $id,
        ?int $offset = 0,
        ?int $limit = 100,
        ?\DateTime $startDate = null,
        ?\DateTime $endDate = null,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourseRuns'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getCourseRuns'
            );
        }







        $resourcePath = '/v3/client/courses/{id}/course-runs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startDate,
            'startDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $endDate,
            'endDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sellOnPortal,
            'sellOnPortal', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCourses
     *
     * Returns a collection of Courses
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourses'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Cinolla\Model\LineItem[]
     */
    public function getCourses(
        ?int $offset = 0,
        ?int $limit = 100,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourses'][0]
    ): array
    {
        list($response) = $this->getCoursesWithHttpInfo($offset, $limit, $sellOnPortal, $contentType);
        return $response;
    }

    /**
     * Operation getCoursesWithHttpInfo
     *
     * Returns a collection of Courses
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourses'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Cinolla\Model\LineItem[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCoursesWithHttpInfo(
        ?int $offset = 0,
        ?int $limit = 100,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourses'][0]
    ): array
    {
        $request = $this->getCoursesRequest($offset, $limit, $sellOnPortal, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Cinolla\Model\LineItem[]', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Cinolla\Model\LineItem[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Cinolla\Model\LineItem[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Cinolla\Model\LineItem[]';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Cinolla\Model\LineItem[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCoursesAsync
     *
     * Returns a collection of Courses
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourses'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCoursesAsync(
        ?int $offset = 0,
        ?int $limit = 100,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourses'][0]
    ): PromiseInterface
    {
        return $this->getCoursesAsyncWithHttpInfo($offset, $limit, $sellOnPortal, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCoursesAsyncWithHttpInfo
     *
     * Returns a collection of Courses
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourses'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCoursesAsyncWithHttpInfo(
        ?int $offset = 0,
        ?int $limit = 100,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourses'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Cinolla\Model\LineItem[]';
        $request = $this->getCoursesRequest($offset, $limit, $sellOnPortal, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCourses'
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  bool|null $sellOnPortal Filter items to only those marked for sale on the Booking Portal. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCourses'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCoursesRequest(
        ?int $offset = 0,
        ?int $limit = 100,
        ?bool $sellOnPortal = null,
        string $contentType = self::contentTypes['getCourses'][0]
    ): Request
    {





        $resourcePath = '/v3/client/courses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sellOnPortal,
            'sellOnPortal', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
