<?php
/**
 * CustomFormsApi
 * PHP version 8.1
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cinolla Client API
 *
 * Welcome to Cinolla Client API documentation for version 3. Please see below for the available API endpoints and their required parameters and responses. If you have any questions, please contact [support@cinolla.com](mailto:support@cinolla.com).
 *
 * The version of the OpenAPI document: 3.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Cinolla\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use SynergiTech\Cinolla\ApiException;
use SynergiTech\Cinolla\Configuration;
use SynergiTech\Cinolla\HeaderSelector;
use SynergiTech\Cinolla\ObjectSerializer;

/**
 * CustomFormsApi Class Doc Comment
 *
 * @package  SynergiTech\Cinolla
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomFormsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getCustomFormSubmissions' => [
            'application/json',
        ],
        'getCustomForms' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getCustomFormSubmissions
     *
     * Get a collection of Custom Form Submissions
     *
     * @param  string $customFormHash The hash of a Custom Form (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string|null $bookingHash Filter results by a single booking (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomFormSubmissions'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Cinolla\Model\CustomFormSubmissions[]
     */
    public function getCustomFormSubmissions(
        string $customFormHash,
        ?int $offset = 0,
        ?int $limit = 100,
        ?string $bookingHash = null,
        string $contentType = self::contentTypes['getCustomFormSubmissions'][0]
    ): array
    {
        list($response) = $this->getCustomFormSubmissionsWithHttpInfo($customFormHash, $offset, $limit, $bookingHash, $contentType);
        return $response;
    }

    /**
     * Operation getCustomFormSubmissionsWithHttpInfo
     *
     * Get a collection of Custom Form Submissions
     *
     * @param  string $customFormHash The hash of a Custom Form (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string|null $bookingHash Filter results by a single booking (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomFormSubmissions'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Cinolla\Model\CustomFormSubmissions[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCustomFormSubmissionsWithHttpInfo(
        string $customFormHash,
        ?int $offset = 0,
        ?int $limit = 100,
        ?string $bookingHash = null,
        string $contentType = self::contentTypes['getCustomFormSubmissions'][0]
    ): array
    {
        $request = $this->getCustomFormSubmissionsRequest($customFormHash, $offset, $limit, $bookingHash, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SynergiTech\Cinolla\Model\CustomFormSubmissions[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Cinolla\Model\CustomFormSubmissions[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Cinolla\Model\CustomFormSubmissions[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SynergiTech\Cinolla\Model\CustomFormSubmissions[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Cinolla\Model\CustomFormSubmissions[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCustomFormSubmissionsAsync
     *
     * Get a collection of Custom Form Submissions
     *
     * @param  string $customFormHash The hash of a Custom Form (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string|null $bookingHash Filter results by a single booking (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomFormSubmissions'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCustomFormSubmissionsAsync(
        string $customFormHash,
        ?int $offset = 0,
        ?int $limit = 100,
        ?string $bookingHash = null,
        string $contentType = self::contentTypes['getCustomFormSubmissions'][0]
    ): PromiseInterface
    {
        return $this->getCustomFormSubmissionsAsyncWithHttpInfo($customFormHash, $offset, $limit, $bookingHash, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCustomFormSubmissionsAsyncWithHttpInfo
     *
     * Get a collection of Custom Form Submissions
     *
     * @param  string $customFormHash The hash of a Custom Form (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string|null $bookingHash Filter results by a single booking (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomFormSubmissions'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCustomFormSubmissionsAsyncWithHttpInfo(
        $customFormHash,
        $offset = 0,
        $limit = 100,
        $bookingHash = null,
        string $contentType = self::contentTypes['getCustomFormSubmissions'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Cinolla\Model\CustomFormSubmissions[]';
        $request = $this->getCustomFormSubmissionsRequest($customFormHash, $offset, $limit, $bookingHash, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCustomFormSubmissions'
     *
     * @param  string $customFormHash The hash of a Custom Form (required)
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string|null $bookingHash Filter results by a single booking (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomFormSubmissions'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCustomFormSubmissionsRequest(
        $customFormHash,
        $offset = 0,
        $limit = 100,
        $bookingHash = null,
        string $contentType = self::contentTypes['getCustomFormSubmissions'][0]
    ): Request
    {

        // verify the required parameter 'customFormHash' is set
        if ($customFormHash === null || (is_array($customFormHash) && count($customFormHash) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $customFormHash when calling getCustomFormSubmissions'
            );
        }





        $resourcePath = '/v3/client/custom-forms/{customFormHash}/submissions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bookingHash,
            'bookingHash', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($customFormHash !== null) {
            $resourcePath = str_replace(
                '{' . 'customFormHash' . '}',
                ObjectSerializer::toPathValue($customFormHash),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCustomForms
     *
     * Get a collection of Custom Forms
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomForms'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Cinolla\Model\CustomForm[]
     */
    public function getCustomForms(
        ?int $offset = 0,
        ?int $limit = 100,
        string $contentType = self::contentTypes['getCustomForms'][0]
    ): array
    {
        list($response) = $this->getCustomFormsWithHttpInfo($offset, $limit, $contentType);
        return $response;
    }

    /**
     * Operation getCustomFormsWithHttpInfo
     *
     * Get a collection of Custom Forms
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomForms'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Cinolla\Model\CustomForm[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCustomFormsWithHttpInfo(
        ?int $offset = 0,
        ?int $limit = 100,
        string $contentType = self::contentTypes['getCustomForms'][0]
    ): array
    {
        $request = $this->getCustomFormsRequest($offset, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SynergiTech\Cinolla\Model\CustomForm[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Cinolla\Model\CustomForm[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Cinolla\Model\CustomForm[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SynergiTech\Cinolla\Model\CustomForm[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Cinolla\Model\CustomForm[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCustomFormsAsync
     *
     * Get a collection of Custom Forms
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomForms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCustomFormsAsync(
        ?int $offset = 0,
        ?int $limit = 100,
        string $contentType = self::contentTypes['getCustomForms'][0]
    ): PromiseInterface
    {
        return $this->getCustomFormsAsyncWithHttpInfo($offset, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCustomFormsAsyncWithHttpInfo
     *
     * Get a collection of Custom Forms
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomForms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCustomFormsAsyncWithHttpInfo(
        $offset = 0,
        $limit = 100,
        string $contentType = self::contentTypes['getCustomForms'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Cinolla\Model\CustomForm[]';
        $request = $this->getCustomFormsRequest($offset, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCustomForms'
     *
     * @param  int|null $offset An offset to return a paginated list of results (optional, default to 0)
     * @param  int|null $limit The limit on the number of results (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCustomForms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCustomFormsRequest(
        $offset = 0,
        $limit = 100,
        string $contentType = self::contentTypes['getCustomForms'][0]
    ): Request
    {




        $resourcePath = '/v3/client/custom-forms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
